### ISSUE TITLE
Handle cases where `WP_CLI::launch_self()` returns an error

### ISSUE THREAD

**Issue by danielbachhuber** [billerickson/wp-cli-plugin-install-missing#10]
In situations where `WP_CLI::launch_self()` could return an error, there should be some corresponding error handling.

**Comment by billerickson** [comment]
Is there a way to pass the error message from `WP_CLI::launch_self()` without repeating the 'Error' prefix? 

With this code (purposeful typo):

```
$response = WP_CLI::launch_self( 'plugin lisst', array(), array( 'format' => 'json', 'status' => 'active' ), false, true );
if( !empty( $response->stderr ) ) {
    WP_CLI::error( $response->stderr );
}
```

I get this error: 

![screenshot](https://s3.amazonaws.com/f.cl.ly/items/3X1P0K2e2z1U320G3U2N/Screen%20Shot%202016-05-27%20at%204.38.08%20PM.png?v=feaafd40)

For now I'll do a str_replace() to remove it, but it would be nice if I could simply do `WP_CLI::error( $response )` and it pulls the error message out of the response.
