### ISSUE TITLE
Consider adding functional tests to this project

### ISSUE THREAD

**Issue by danielbachhuber** [billerickson/wp-cli-plugin-install-missing#5]
Functional tests are an integral ingredient of highly-quality, maintainable commands. WP-CLI tries to make it as easy as possible to add functional tests to your package with its `wp scaffold package-tests` command:

https://github.com/wp-cli/scaffold-package-command#wp-scaffold-package-tests

I'd encourage you to consider adding functional tests to your package :) By starting your functional tests early on, it also makes it much easier to maintain your project over time.

**Comment by billerickson** [comment]
Will do!

**Comment by billerickson** [comment]
Some examples for guidance:

https://github.com/runcommand/dist-archive/blob/master/features/dist-archive.feature
https://github.com/runcommand/doctor/blob/master/features/diagnose-core-update.feature
